services:
  - type: web
    name: omega-titan-server
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn staline_server:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: STALINE_API_KEY
        value: STALINE-ULTRA-KEY-2025
      - key: FINNHUB_API_KEY
        value: ""
      - key: PYTHON_VERSION
        value: "3.11.0"
